# Generated by Django 5.2.17 on 2026-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("store_id", models.SmallIntegerField()),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("address_id", models.SmallIntegerField()),
                ("activebool", models.BooleanField(default=True)),
                ("create_date", models.DateField()),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("active", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("staff_id", models.SmallIntegerField()),
                ("rental_id", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("payment_date", models.DateTimeField()),
            ],
            options={
                "db_table": "payment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                ("rental_id", models.AutoField(primary_key=True, serialize=False)),
                ("rental_date", models.DateTimeField()),
                ("inventory_id", models.IntegerField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("staff_id", models.SmallIntegerField()),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rental",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_type", models.CharField(max_length=100)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "precision_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "recall_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "f1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "silhouette",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("features", models.TextField(blank=True, null=True)),
                ("file_path", models.CharField(max_length=255)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ML Model Info",
                "verbose_name_plural": "ML Model Info",
                "db_table": "model_info",
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerOLAP",
            fields=[
                ("customer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("store_id", models.SmallIntegerField(default=1)),
                (
                    "total_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "min_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("rental_count", models.IntegerField(default=0)),
                ("distinct_films", models.IntegerField(default=0)),
                (
                    "avg_rental_duration_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_rental_date", models.DateTimeField(blank=True, null=True)),
                ("recency_days", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("segment", models.CharField(blank=True, max_length=32, null=True)),
                ("cluster", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer OLAP",
                "verbose_name_plural": "Customer OLAP Records",
                "db_table": "customer_olap",
                "indexes": [
                    models.Index(
                        fields=["segment"], name="customer_ol_segment_9da5aa_idx"
                    )
                ],
            },
        ),
    ]
